### ISSUE TITLE
enum syntax highlighting not working

### ISSUE THREAD

**Issue by guilhermedeandrade** [pantharshit00/vim-prisma#2]
Hey there! 👋 First of all, thanks a lot for the plugin! 

I've just installed and I realized that the enum syntax highlighting is not working. Is is supported?

<img width="704" alt="image" src="https://user-images.githubusercontent.com/8797405/81488834-4d55a780-9266-11ea-9a78-88ec7a0f95e0.png">

I am using `NVIM v0.4.3`

**Comment by pantharshit00** [comment]
Hi, it might be your theme, try again with a different there. 

Otherwise, please paste the datamodel here so that I can test it

**Comment by pantharshit00** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/22195362/81498195-1a042e80-92e1-11ea-83f2-dcf61e9c16a5.png">

It works for me now. Although, I am not very happy with the grammar that this plugin use. I am planning a rewrite.

**Comment by guilhermedeandrade** [comment]
Oh, that definitely seems like a problem with the Dracula theme! I will try it with another theme as you suggested, thanks.

**Comment by guilhermedeandrade** [comment]
Just a quick follow up: it is indeed a problem with the theme! Just tested it using Gruvbox and it worked great.
