### ISSUE TITLE
Add this plugin to vim-polyglot

### ISSUE THREAD

**Issue by kkoomen** [pantharshit00/vim-prisma#6]
Hi,

Thanks for the work you put into doing the ftdetect + syntax. I personally use [vim-polyglot](https://github.com/sheerun/vim-polyglot) to get advanced plugin support for all languages I use. Can you make a PR to vim-polyglot to add this plugin? That's be really useful.

Thanks.

**Comment by pantharshit00** [comment]
Feel free to make a PR to vim-polygot. I personally don't use it so I won't spend time on doing that.
